---
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Application template for Apache ActiveMQ. See https://hub.docker.com/r/webcenter/activemq/
      for more information.
    tags: instant-app,3rd-party,javaee,java
    version: 1.0.0
  name: activemq
labels:
  template: activemq
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  value: activemq
  required: true
- description: 'Custom hostname for service routes.  Leave blank for default hostname,
    e.g.: <application-name>.<project>.<default-domain-suffix>'
  name: APPLICATION_HOSTNAME
  value: ''
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
      template: openshift-activemq-useroot
  spec:
    strategy:
      type: Rolling
    replicas: 1
    selector:
      deploymentConfig: "${APPLICATION_NAME}"
    template:
      metadata:
        name: "${APPLICATION_NAME}"
        labels:
          deploymentConfig: "${APPLICATION_NAME}"
          app: "${APPLICATION_NAME}"
          template: openshift-activemq-useroot
      spec:
        serviceAccountName: "${APPLICATION_NAME}-serviceaccount"
        automountServiceAccountToken: false
        containers:
        - name: "${APPLICATION_NAME}"
          image: "docker.io/webcenter/activemq:latest"
          ports:
          - containerPort: 8161
            protocol: TCP
          - containerPort: 61616
            protocol: TCP
          - containerPort: 61616
            protocol: TCP
- kind: Service
  apiVersion: v1
  spec:
    ports:
    - name: 8161-tcp
      protocol: TCP
      port: 8161
      targetPort: 8161
      nodePort: 0
    - name: 61616-tcp
      protocol: TCP
      port: 61616
      targetPort: 61616
      nodePort: 0
    - name: 61613-tcp
      protocol: TCP
      port: 61613
      targetPort: 61613
      nodePort: 0
    selector:
      deploymentConfig: "${APPLICATION_NAME}"
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
      template: openshift-activemq-useroot
    annotations:
      description: The web server's http port.
- kind: Route
  apiVersion: v1
  id: "${APPLICATION_NAME}-http-route"
  metadata:
    name: "${APPLICATION_NAME}-http-route"
    labels:
      app: "${APPLICATION_NAME}"
      template: openshift-activemq-useroot
    annotations:
      description: Route for application's http service.
  spec:
    host: "${APPLICATION_HOSTNAME}"
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
      weight: 100
    port:
      targetPort: 8161-tcp
    wildcardPolicy: None
- kind: ServiceAccount
  apiVersion: v1
  id: "${APPLICATION_NAME}-serviceaccount"
  metadata:
    name: "${APPLICATION_NAME}-serviceaccount"
    labels:
      app: "${APPLICATION_NAME}"
      template: openshift-activemq-useroot
