FROM tomcat:9-jre8-alpine

MAINTAINER "Vorname <test@mail.com.ch>"

#ADD server.xml /usr/local/tomcat/conf/
#ADD tomcat-users.xml /usr/local/tomcat/conf/
#ADD ojdbc6.jar /usr/local/tomcat/lib/
ADD app.war /usr/local/tomcat/webapps/